stages:
  - tests

tests:
  stage: tests
  script:
    - echo "Activating virtual environment..."
    - source $HOME/providentia-env/bin/activate
    - export PYTHONPATH=$(pwd):${PYTHONPATH}
    - echo "Running unit tests..."
    - coverage run -m pytest tests