stages:
  - tests

tests:
  stage: tests
  script:
    - echo "Activating virtual environment..."
    - conda activate $HOME/providentia-env
    - export PYTHONPATH=$(pwd):${PYTHONPATH}
    - echo "Running unit tests..."
    - python -m coverage run -m pytest tests