stages:
  - tests

tests:
  stage: tests
  script:
    - echo "Activating virtual environment..."
    - conda activate $HOME/providentia-env
    - export PYTHONPATH=$(pwd):${PYTHONPATH}
    - echo "Running unit tests..."
    - coverage run -m pytest tests
    - coverage report -i -m
  coverage: '/^TOTAL\s*\d+\s+\d+\s+(\d+)/'