name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: input
    id: commit
    attributes:
      label: Commit
      description: What commit of our software are you running? Run git log in the terminal and copy commit hash.
    validations:
      required: true
  - type: checkboxes
    id: machines
    attributes:
      label: What machines are you seeing the problem on?
      options:
        - label: Local
        - label: Nord4
        - label: MN5
    validations:
      required: true
  - type: checkboxes
    id: mode
    attributes:
      label: What mode are you seeing the problem on?
      options:
        - label: Download
        - label: Interpolation
        - label: Dashboard
        - label: Report
        - label: Library    
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Configuration file
      description: Please copy and paste your configuration file. This will be automatically formatted into code, so no need for backticks.
      render: bash
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
      accept: .png, .jpg, .jpeg
