[ACTRIS-CAMS]
framework = actris/actris
species = nitrogen dioxide mass concentration
resolution = hourly
model = cams_forecast_ensemble (CAMS)
domain = regional
start_date = 20230601
end_date = 20230701
report_type = standard
report_summary = True
report_stations = False
report_filename = PROVIDENTIA_Report
report_title = Report
temporal_colocation = True
observations_data_label = Nitrogen Dioxide Mass Concentration
forecast = day
dl_interpolated = False
dl_mode = both
dl_thredds_update = False