[ACTRIS-CAMS]
network = actris/actris
species = sconcno2
resolution = hourly
experiments = cams_forecast_ensemble
domain = regional
start_date = 20230602
end_date = 20230701
report_type = standard
report_summary = True
report_stations = False
report_filename = PROVIDENTIA_Report
report_title = Report
temporal_colocation = True
observations_data_label = Nitrogen Dioxide Mass Concentration
forecast = daily
interpolated = false