[bdrc_zamg_wrf_chem]
model = bdrc_zamg_wrf_chem
species = od550aero
resolution = 3hourly
start_date = 20230201
end_date = 20230202
domain = regional
dl_overwrite = True

[bdrc_wrf_nemo]
model = bdrc_wrf_nemo
species = od550aero
resolution = 3hourly
start_date = 20230211
end_date = 20230212
domain = regional
dl_overwrite = True

[bdrc_silam]
model = bdrc_silam
species = od550aero
resolution = 3hourly
start_date = 20230101
end_date = 20230102
domain = regional
dl_overwrite = True

[bdrc_noa]
model = bdrc_noa
species = od550aero
resolution = 3hourly
start_date = 20230101
end_date = 20230102
domain = regional
dl_overwrite = True

[bdrc_ncep_gefs] 
model = bdrc_ncep_gefs
species = od550aero
resolution = 3hourly
start_date = 20230101
end_date = 20230102
domain = regional
dl_overwrite = True

[bdrc_nasa_geos] # hay un dia que es NASA-GEOS_BAK.nc
model = bdrc_nasa_geos
species = od550aero
resolution = 3hourly
start_date = 20230101
end_date = 20230102
domain = regional
dl_overwrite = True

[bdrc_metoffice_um]
model = bdrc_metoffice_um
species = od550aero
resolution = 3hourly
start_date = 20230101
end_date = 20230102
domain = regional
dl_overwrite = True

[bdrc_multi_model]
model = bdrc_multi_model
species = od550aero
resolution = 3hourly
start_date = 20230101
end_date = 20230102
domain = regional
dl_overwrite = True

# [bdrc_monarch] # poner ending, despues de generale lista a tito
# model = bdrc_monarch
# species = od550aero
# resolution = 3hourly
# start_date = 20230101
# end_date = 20230102
# domain = regional
# dl_overwrite = True

[bdrc_mocage]
model = bdrc_mocage
species = od550aero
resolution = 3hourly
start_date = 20230101
end_date = 20230102
domain = regional
dl_overwrite = True

[bdrc_lotos_euros]
model = bdrc_lotos_euros
species = od550aero
resolution = 3hourly
start_date = 20230101
end_date = 20230102
domain = regional
dl_overwrite = True

[bdrc_icon_art]
model = bdrc_icon_art
species = od550aero
resolution = 3hourly
start_date = 20230101
end_date = 20230102
domain = regional
dl_overwrite = True

[bdrc_ema_regcm4]
model = bdrc_ema_regcm4
species = od550aero
resolution = 3hourly
start_date = 20230812
end_date = 20230813
domain = regional
dl_overwrite = True

[bdrc_dream8_cams] 
model = bdrc_dream8_cams
species = od550aero
resolution = 3hourly
start_date = 20230101
end_date = 20230102
domain = regional
dl_overwrite = True

[bdrc_cams_ifs]
model = bdrc_cams_ifs
species = od550aero
resolution = 3hourly
start_date = 20230101
end_date = 20230102
domain = regional
dl_overwrite = True

[bdrc_bsc_dream8b] # poner ultima fecha # 2010 to 11 de 2012 BSC_DREAM8b.nc
model = bdrc_bsc_dream8b
species = od550aero
resolution = 3hourly
start_date = 20220101
end_date = 20220102
domain = regional
dl_overwrite = True

[bdrc_aladin]  # poner ultima fecha
model = bdrc_aladin
species = od550aero
resolution = 3hourly
start_date = 20230310
end_date = 20230311
domain = regional
dl_overwrite = True