[EEA]
network = EEA 
ghost_version = 1.6
species =  sconco3 
resolution = hourly 
start_date = 20231201
end_date = 20240101
domain = global
map_extent = -30, 50, 20, 90
model = cams_forecast (camsf) 
dl_interpolated = False 
#forecast = daily 
#resampling_resolution = 3hourly 
temporal_colocation = True 
spatial_colocation = False 
report_type = cams2_82_bis
report_summary = True
report_stations = False
report_title = CAMS2_82_bis_2024_DJF_EEA_qa
report_filename = CAMS2_82_bis_2024_DJF_EEA_qa
statistic_mode = Temporal|Spatial
statistic_aggregation = Median
periodic_statistic_mode = Independent
periodic_statistic_aggregation = Median
timeseries_statistic_aggregation = Median
Joly-Peuch_classification_code = 1,2 
interp_model_upsampling = gaps

    [[qa_none]]
    qa = 
    
    [[qa_standard]]
    
    [[qa_strict]]
    qa = 23,90,91,92,114,127,128,129,130,131
    