[cams_analysis_ensemble-regional]
start_date = 20250701
end_date = 20250801
species = sconcno2
experiments = cams_analysis_ensemble
domain = regional
resolution = hourly
network = eea/eionet
interpolated = False

[cams_forecast_ensemble-regional] 
start_date = 20250701 
end_date = 20250702
species = sconcno2
experiments = cams_forecast_ensemble
domain = regional
resolution = hourly
network = eea/eionet
interpolated = False

[cams_forecast-global-3hourly]
ghost_version = 1.3.2 
start_date = 20200601  
end_date = 20200701
species = sconcno2
experiments = cams_forecast
domain = global
resolution = 3hourly
network = EEA_AQ_eReporting 
interpolated = False

[cams_forecast-global-hourly]
start_date = 20171201 # broken 
end_date = 20180101
species = sst
experiments = cams_forecast
domain = global
resolution = hourly
network = NOAA_ISD_IP
interpolated = False

[cams_reanalysis_ensemble_interim-regional]
start_date = 20240101 # broken
end_date = 20240301
species = sconcno2
experiments = cams_reanalysis_ensemble_interim
domain = regional
resolution = hourly
network = eea/eionet
interpolated = False

[cams_reanalysis_ensemble_validated-regional] 
ghost_version = 1.3.3
start_date = 20200101 
end_date = 20200301
species = sconcno2
experiments = cams_reanalysis_ensemble_validated
domain = regional
resolution = hourly
network = EBAS
interpolated = False

[cams_reanalysis-global]
ghost_version = 1.3.2
start_date = 20181101
end_date = 20181130
species = sconcno2
experiments = cams_reanalysis
domain = global
resolution = 3hourly
network = EBAS
interpolated = False