[CAMS2_40_ICAP]
network = eea/eionet
species = sconco3,sconcno2,sconcco,sconcso2,pm10,pm2p5
resolution = hourly
start_date = 20250801
end_date = 20250827
experiments = a00d_cirrus-regional-000, a00e_cirrus-regional-av_an, a8mw-global-000 (FC-U9, AN-U9, ICAP-U2)
temporal_colocation = True
spatial_colocation = False
report_type = operational_test_weekly
report_summary = True
report_stations = False
report_title = CAMS2_40 forecast & analysis & ICAP Report
report_filename = cams_icap_20250801_20250827_eea_eionet_operational.pdf
statistic_mode = Flattened
statistic_aggregation = Median
timeseries_statistic_aggregation = Median
station_classification = keep: background || remove: industrial, traffic, unknown
