[CAMS2_40]
network = eea/eionet
species = pm10, pm2p5
resolution = hourly
start_date = 20241201
end_date = 20250228
experiments = a00d_cirrus-regional-000, a823_a8mw-global-000 (FC-U9, ICAP-U2)
temporal_colocation = True
spatial_colocation = False
report_type = operational_test_3monthly
report_summary = True
report_stations = False
report_title = CAMS2_40 DJF U9 Report
report_filename = cams_icap_operational_DJF_eea_eionet_pm.pdf
statistic_mode = Flattened
statistic_aggregation = Median
timeseries_statistic_aggregation = Median
#station_classification = keep: background || remove: industrial, traffic, unknown

    [[All]]
    #map_extent = -25, 30, 36.5, 75
    country= keep: andorra, norway, sweden, denmark, finland, iceland, estonia, lithuania, france, united kingdom, ireland, belgium, netherlands, luxembourg, portugal, spain, italy, greece, malta, cyprus, germany, austria, switzerland, poland, hungary, czech republic, slovakia (slovak republic), romania, bulgaria,croatia (local name: hrvastska), kosovo, bosnia - herzegovina, montenegro, slovenia||
    station_classification = keep: background || remove: industrial, traffic, unknown

    [[Europe_North]]
    #longitude = -30, 35
    #latitude = 54, 75
    #map_extent = -30, 35, 54, 75
    country= keep: norway, sweden, denmark, finland, iceland, estonia, lithuania||
    station_classification = keep: background || remove: industrial, traffic, unknown

    [[Europe_West]]
    #longitude = -10, 15
    #latitude = 45, 55
    #map_extent = -10, 15, 45, 55
    country= keep: france, united kingdom, ireland, belgium, netherlands, luxembourg||
    station_classification = keep: background || remove: industrial, traffic, unknown

    [[Europe_South]]
    #longitude = -10, 30
    #latitude = 35, 45
    #map_extent = -10, 30, 35, 45
    country= keep: portugal, spain, italy, greece, malta, cyprus, andorra||
    station_classification = keep: background || remove: industrial, traffic, unknown

    [[Europe_Center]]
    #longitude = 5, 25
    #latitude = 45, 55
    #map_extent = 5, 25, 45, 55
    country= keep: germany, austria, switzerland, poland, hungary, czech republic, slovakia (slovak republic),slovenia||
    station_classification = keep: background || remove: industrial, traffic, unknown

    [[Europe_East]]
    #longitude = 15, 35
    #latitude = 40, 55
    #map_extent = 15, 35, 40, 55
    country= keep: romania, bulgaria, croatia (local name: hrvastska), bosnia - herzegovina, montenegro, kosovo||
    station_classification = keep: background || remove: industrial, traffic, unknown
