[cams2_82_nrt_du_ss_no_interpolated]
#network = nasa-aeronet/oneill_v3-lev15
interp_n_neighbours = 4
start_date = 202301
end_date = 202601
species = od500aerocoarse
model = osuite_du_ss
domain = global
resolution = 3hourly