[DEBUG]
network = NOAA_ISD
species = t2
resolution = hourly
start_date = 20180101
end_date = 20180201
model = era5_reanalysis-global
dl_overwrite = true
dl_mode = both
dl_interpolated = False
dl_ghost_source = bsc