[SEMINAR]
network = GHOST
species = t2@sconco3
resolution = hourly
start_date = 20180101
end_date = 20180201
model = era5_reanalysis-global
#dl_mode = mod
#dl_interpolated = False
#dl_overwrite = True