[LSP]
ghost_version = 1.6
network = GHOST
#species = t2@sconco3, td2@sconco3, u10@sconco3, v10@sconco3, pblh@sconco3, tphdyn@sconco3, aswin@sconco3, aswindir@sconco3, aswtoa@sconco3  
species = u10@sconco3, v10@sconco3, pblh@sconco3, tphdyn@sconco3, aswin@sconco3, aswindir@sconco3, aswtoa@sconco3
#species = auvin@sconco3, cld@sconco3, clddf@sconco3, photi@sconco3, slp@sconco3, acprec@sconco3, spd10@sconco3, gust10@sconco3, sst@sconco3, cfracmax@sconco3, cldbot@sconco3, cldtop@sconco3
resolution = hourly
start_date = 20180101
end_date = 20180201
model = era5_reanalysis-global
dl_mode = mod
dl_interpolated = False
dl_overwrite = True
interp_cleanup = True