[SEMINAR]
network = NOAA_ISD
species = t2
resolution = hourly
start_date = 20180101
end_date = 20180201
model = era5_reanalysis-global
report_type = seminar
report_stations = True
interp_n_neighbours = 1

[[Japan]]
country = Japan

[[Spain]]
country = Spain