[ICAP]
network = AERONET_v3_lev1.5
species = od550aero
resolution = hourly
model_resolution = 6hourly
start_date = 20180101
end_date = 20221001
model = icap_ensemble-global
dl_mode = mod
dl_interpolated = False
dl_overwrite = False
