[NEW]
ghost_version = default
interp_n_neighbours = default
start_date = 202508
end_date = 202509
species = sconco3,sconcno2,pm10,pm2p5,sconcco,sconcso2
experiments = a00d_cirrus
domain = regional
ensemble_options = default
network = eea/eionet
resolution = hourly
interpolated= True

