[JEDI]
network = ineris/eionet-cams2_40-vra-validation
species = pm10
resolution = hourly
start_date = 20240101
end_date = 20250101
model = aagd-regional-av, aagd-regional-av_an, aas5-regional-av, aas5-regional-av_an, vind_mr_4Dlt_uni_05-regional-an, vind_mr_4Dlt_uni_06-regional-an, vind_mr_4Dlt_uni_07-regional-an, vind_mr_4Dlt_uni_08-regional-an
#model = aagd-regional-av, aagd-regional-av_an, aas5-regional-av, aas5-regional-av_an, vind_mr_4Dlt_uni_06-regional-an, vind_mr_4Dlt_uni_07-regional-an, vind_mr_4Dlt_uni_08-regional-an
#model = aagd-regional-av, aagd-regional-av_an, aas5-regional-av, aas5-regional-av_an, vind_mr_4Dlt_uni_05-regional-an, vind_mr_4Dlt_uni_06-regional-an, vind_mr_4Dlt_uni_07-regional-an
#model = vind_mr_4Dlt_uni_05-regional-an
temporal_colocation = True
spatial_colocation = True
statistic_mode = Flattened