[All]
network = eea/eionet
ghost_version = 1.5
species = sconco3 #,sconco3,sconcco,pm10,pm2p5
resolution = hourly # daily for interpolation, hourly/3hourly for download
start_date = 20230101
end_date = 20230201
map_extent = -180, 180, -90, 90
experiments = a59g-regional-000 # cams_reanalysis for EAC4 reanalysis; cams_forecast for forecast
interp_n_neighbours = default
interpolated = False # download non interpolated experiments
forecast = day1,day4 # for interpolation: will interpolate all forecast data available (no matter what is set here)
temporal_colocation = True
spatial_colocation = True
report_type = cams2_82_bis
report_summary = True
report_stations = False
report_title = CAMS2_82_bis_2024_MAM
report_filename = CAMS2_82_bis_2024_MAM
statistic_aggregation = Median
periodic_statistic_mode = Independent
periodic_statistic_aggregation = Median
timeseries_statistic_aggregation = Median

    [[Aggregation_temporal_spatial]]
    statistic_mode = Temporal|Spatial

    [[Aggregation_spatial_temporal]]
    statistic_mode = Spatial|Temporal

    [[Aggregation_Flattened]]
    statistic_mode = Flattened