[DL]
ghost_version = 1.6
network = EEA
species = sconco3, sconcno2
resolution = hourly
start_date = 20230101
end_date = 20230201
model = a59j-regional-006, a59g-regional-000
forecast = day

[INTERP1]
ghost_version = 1.6
network = EEA
species = sconco3
resolution = hourly
start_date = 202301
end_date = 202302
model = a59j-regional-006

[INTERP2]
ghost_version = 1.6
network = EEA
species = sconco3, sconcno2
resolution = hourly
start_date = 20230101
end_date = 20230201
model = a59j-regional-006, a59g-regional-000
forecast = day
interp_n_neighbours = 8

[INTERP3]
ghost_version = 1.6
network = EEA
species = sconcno2
resolution = daily
start_date = 20230101
end_date = 20230201
model = a59g-regional-000
forecast = day
interp_n_neighbours = 12  
interp_model_downsampling = median
model_resolution = hourly 

[DASHBOARD1]
ghost_version = 1.6
network = EEA
species = sconco3
resolution = hourly
start_date = 20230101
end_date = 20230201
model = a59g-regional-000
country = keep: Spain

[DASHBOARD2]
ghost_version = 1.6
network = EEA
species = sconco3
resolution = hourly
start_date = 20230101
end_date = 20230201
model = a59g-regional-000, a59j-regional-006
all_representativity_percent = 40
period = keep: Daytime
GSFC_coastline_proximity = -1, 2

[DASHBOARD3]
ghost_version = 1.6
network = EEA
species = sconcno2
resolution = hourly
start_date = 20230101
end_date = 20230201
model = a59g-regional-000
resampling_resolution = 3hourly
country = keep: United Kingdom, Ireland
GSFC_coastline_proximity = -1, 2
forecast = day

[REPORT1]
ghost_version = 1.6
network = EEA
species = sconco3
resolution = hourly
start_date = 20230101
end_date = 20230201
model = a59j-regional-006
area_classification = keep: rural
country = keep: Spain
report_type = training
report_filename = Report1

[REPORT2]
ghost_version = 1.6
network = EEA
species = sconco3
resolution = hourly
start_date = 20230101
end_date = 20230201
model = a59g-regional-000
forecast = day
report_type = training2
report_filename = Report2

    [[Mediterranean]]
    longitude = -5, 38
    latitude = 32, 43
    map_extent = -6, 39, 32, 44

    [[Scandanavia]]
    longitude = -1, 32
    latitude = 55, 71

[REPORT3]
ghost_version = 1.6
network = EEA
species = sconco3
resolution = hourly
start_date = 20230101
end_date = 20230201
filter_species = EEA:sconcno2 (:, <2.0, nan)
model = a59j-regional-006
report_type = training3
altitude = 0, 1000
report_filename = Report3
area_classification = keep: rural
#longitude = -15, 40
#latitude = 35, 61
