[ACTRIS]
framework = actris/actris
resolution = monthly
start_date = 20100101
end_date = 20250101
temporal_colocation = False
spatial_colocation = True
report_type = actris_test
report_summary = True
report_stations = False
report_filename = PROVIDENTIA_Report
report_title = Report
dl_overwrite = True
dl_thredds_update = True