#[cams_forecast-global-3hourly-lbsco532] # same units error m-1 sr-1, removing the star parts does not solve it but it submits
#start_date = 20200601  
#end_date = 20200701
#species = lbsco532 # m-1 sr-1
#experiments = cams_forecast
#domain = global
#resolution = hourly
#model_resolution = 3hourly
#network = EBAS # Mm-1
#interpolated = False
#ghost_version = 1.5.1

[cams_forecast-global-hourly-si] #m of water, removing the star parts does not solve it but it submits
start_date = 20171201  
end_date = 20180101
species = si # m
experiments = cams_forecast
domain = global
resolution = hourly
model_resolution = hourly
network = NOAA_ISD # cm
interpolated = False

[cams_forecast-global-hourly-vdist] #its supposed to have km but it is downloaded as m
start_date = 20171201  
end_date = 20180101
species = vdist # m
experiments = cams_forecast
domain = global
resolution = hourly
model_resolution = hourly
network = NOAA_ISD # m
interpolated = False

[cams_forecast-global-hourly-t2]
start_date = 20171201  
end_date = 20180101
species = t2 # K
experiments = cams_forecast
domain = global
resolution = hourly
model_resolution = hourly
network = NOAA_ISD # K
interpolated = False

[cams_forecast-global-hourly-cldbot]
start_date = 20171201  
end_date = 20180101
species = cldbot # m 
experiments = cams_forecast
domain = global
resolution = hourly
model_resolution = hourly
network = NOAA_ISD # m
interpolated = False

[cams_forecast-global-hourly-pshltr] 
start_date = 20171201  
end_date = 20180101
species = pshltr # Pa
experiments = cams_forecast
domain = global
resolution = hourly
model_resolution = hourly
network = NOAA_ISD # hPa
interpolated = False

[cams_reanalysis-global-td2]
start_date = 20181101
end_date = 20181201
species = td2 # K
experiments = cams_reanalysis
domain = global
resolution = hourly
model_resolution = 3hourly
network = NOAA_ISD # K
interpolated = False

[cams_reanalysis-global-pshltr]
start_date = 20181101
end_date = 20181201
species = pshltr # Pa
experiments = cams_reanalysis
domain = global
resolution = hourly
model_resolution = 3hourly
network = NOAA_ISD # hPa
interpolated = False