[EEA]
network = EEA #CHILE_SINCA,CNEMC,US_EPA_AQS,GHOST #,CHILE_SINCA,CNEMC,EEA,US_EPA_AQS,GHOST,CHILE_SINCA,CNEMC,EEA,US_EPA_AQS,GHOST
ghost_version = 1.6
species =  sconco3 #,sconcno2,sconcco,pm10,pm2p5 #sconco3,sconco3,sconco3,sconco3,sconco3,sconcno2,sconcno2,sconcno2,sconcno2,sconcno2,sconcco,sconcco,sconcco,sconcco,sconcco #,pm10,pm2p5
resolution = hourly # daily/hourly for interpolation, hourly/3hourly for download, hourly for report
start_date = 20231201
end_date = 20240301
domain = global
map_extent = -30, 50, 20, 90
experiments = cams_forecast (camsf) #camsr for EAC4 reanalysis; camsf for forecast
ensemble = default
interp_n_neighbours = default
interpolated = False # download non interpolated experiments
forecast = daily # for interpolation: will interpolate all forecast data available (no matter what is set here)
resampling_resolution = 3hourly # resample to this resolution when doing a report

temporal_colocation = True # between exp and obs
spatial_colocation = False # across species
report_type = cams2_82_bis
report_summary = True
report_stations = False
report_title = CAMS2_82_bis_2024_DJF_EEA_qa
report_filename = CAMS2_82_bis_2024_DJF_EEA_qa
statistic_mode = Temporal|Spatial
statistic_aggregation = Median
periodic_statistic_mode = Independent
periodic_statistic_aggregation = Median
timeseries_statistic_aggregation = Median

Joly-Peuch_classification_code = 1,2 # filtering by Joly-Peuch classification

    [[qa_none]]
    qa = 
    
    [[qa_standard]]
    
    [[qa_strict]]
    qa = 23,90,91,92,114,127,128,129,130,131
    