#[FORECAST]
#network = eea/eionet
#species = sconco3
#resolution = hourly
#start_date = 20230101
#end_date = 20230201
#experiments = a59g-regional-000
#temporal_colocation = True
#spatial_colocation = True
#statistic_mode = Temporal|Spatial
#forecast = daily
#forecast = combined
#forecast = day
#report_type = operational

[SECTION22]
network = eea/eionet
start_date = 20230101
end_date = 20230201
species = sconco3
resolution = hourly
experiments = a59g, a59j
domain = regional
ensemble = 000, 006