[DEBUG]
network = BJMEMC, CANADA_NAPS, CHILE_SINCA, CNEMC, EANET, EBAS, EEA_AQ_eReporting
resolution = hourly
start_date = 20170101
end_date = 20200101
experiments = cams61_emep_ph2-eu-000, cams61_monarch_ph2-eu-000, cams61_silam_ph2-eu-000 (EMEP, MONARCH, SILAM)
species = sconco3