[INTERP]
network = eea/eionet
species = sconco3
resolution = hourly
start_date = 20180101
end_date = 20190101
model = cams61_emep_ph2-eu, cams61_monarch_ph2-eu
temporal_colocation = True
spatial_colocation = True
report_type = operational