[INTERP]
network = NOAA_ISD_EU
species = t2
resolution = hourly
start_date = 20180101
end_date = 20190101
model = era5_reanalysis-global
temporal_colocation = True
spatial_colocation = True
report_type = operational