[INTERP]
network = eea/eionet
species = sconco3
resolution = hourly
model_resolution = 3hourly
start_date = 20231201
end_date = 20240101
model = cams_forecast-global
temporal_colocation = True
spatial_colocation = True
report_type = operational
forecast = daily