[SECTION1]
network = EBAS
species = sconco3
resolution = hourly
start_date = 20180101
end_date = 20190101
temporal_colocation = True
spatial_colocation = True
active_dashboard_plots = timeseries,None,metadata,statsummary
#active_dashboard_plots = None,None,None,None

