[FORECAST]
network = eea/eionet
species = sconco3
resolution = hourly
start_date = 20230101
end_date = 20230201
experiments = a59g-regional-000#, a59j-regional-006
temporal_colocation = True
spatial_colocation = True
statistic_mode = Spatial|Temporal
#forecast = daily
#forecast = combined
#forecast = day
report_type = operational