[FORECAST]
network = eea/eionet
species = sconco3
resolution = hourly
start_date = 20230101
end_date = 20230201
model = a59g-regional-000, a59j-regional-006 (fc, notfc)
temporal_colocation = True
spatial_colocation = True
forecast = daily
report_type = operational