[TRAINING]
ghost_version = 1.6
network = EEA
species = sconco3, sconcno2
resolution = hourly
start_date = 20230101
end_date = 20230201
model = a59j-regional-006, a59g-regional-000
report_type = training
report_summary = True
report_stations = False