[DEBUG]
species = tphclp
resolution = hourly
start_date = 20180101
end_date = 20180201
model = era5_tropopause-global
dl_overwrite = true
dl_mode = both
dl_interpolated = False
dl_ghost_source = bsc

