[cams_analysis_ensemble-regional]
start_date = 20250701
end_date = 20250801
species = sconcno2
network = eea/eionet
experiments = cams_analysis_ensemble
domain = regional
resolution = hourly

[cams_forecast_ensemble-regional]
start_date = 20250701
end_date = 20250702
species = sconcno2
network = eea/eionet
experiments = cams_forecast_ensemble
domain = regional
resolution = hourly
forecast = daily