[TRAINING]
network = nasa-aeronet/directsun_v3-lev15
species = od550aero
resolution = 3hourly
start_date = 20250701
end_date = 20260101
model = osuite-global-000, a00k_cirrus-regional-000
upper_bound = 1
statistic_mode = Flattened

    [[All stations]]
    map_extent = -180, 180, -90, 90

    [[Kuwait]]
    station_reference = Kuwait_University_2
    map_extent = 30, 60, 10, 35