[TRAINING]
network = nasa-aeronet/directsun_v3-lev15
species = od550aero
resolution = 3hourly
start_date = 20250101
end_date = 20250801
model = a00c_cirrus-regional-000
report_type = kuwait
report_summary = True
report_stations = False