[TRAINING]
network = nasa-aeronet/directsun_v3-lev15
species = od550aero
resolution = 3hourly
start_date = 20250101
end_date = 20250701
model = osuite-global-000, a8xy-regional-000

    [[All]]

    [[Kuwait]]
    station_reference = Kuwait_University_2