[DL1]
model = a59g-regional-000, a59j-regional-006
species = sconco3, sconcno2
resolution = hourly
start_date = 20230101
end_date = 20230201

[DL2]
ghost_version = 1.6
network = EEA
species = sconco3, sconcno2
resolution = hourly, daily
start_date = 20230101
end_date = 20230201

[DL3]
ghost_version = 1.6
network = EEA
species = sconco3, sconcno2
resolution = hourly, daily
start_date = 20230101
end_date = 20230201
model = a59g-regional-000, a59j-regional-006
dl_mode = both
dl_interpolated = false
dl_ghost_source = bsc
dl_overwrite = true

[DL4]
ghost_version = 1.6
network = EEA
species = sconco3, sconcno2
resolution = *
start_date = 20230101
end_date = 20230201