[REPORT1]
ghost_version = 1.6
network = EEA
species = sconco3
resolution = hourly
start_date = 20230101
end_date = 20230201
model = a59j-regional-006
area_classification = keep: rural
country = keep: Spain
report_type = training
report_filename = Report1

[REPORT2]
ghost_version = 1.6
network = EEA
species = sconco3
resolution = hourly
start_date = 20230101
end_date = 20230201
model = a59g-regional-000
forecast = day
report_type = training2
report_filename = Report2

    [[Mediterranean]]
    longitude = -5, 38
    latitude = 32, 43
    map_extent = -6, 39, 32, 44

    [[Scandanavia]]
    longitude = -1, 32
    latitude = 55, 71

[REPORT3]
ghost_version = 1.6
network = EEA
species = sconco3
resolution = hourly
start_date = 20230101
end_date = 20230201
filter_species = EEA:sconcno2 (:, <2.0, nan)
model = a59j-regional-006
report_type = training3
altitude = 0, 1000
report_filename = Report3
area_classification = keep: rural
